kind: SecurityContextConstraints
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/description: extends the anyuid with caps 
  creationTimestamp: null
  name: customscc
priority: 10
readOnlyRootFilesystem: false
addCapabilities:
- CAP_SYS_PACCT
requiredDropCapabilities:
- MKNOD
- SYS_CHROOT
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:random:default
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- secret
